/**
 * SED - Semantic Entropy Differencing
 * CLI Markdown Report Generator
 * Copyright (C) 2026 Stevo (sgbilod)
 * @license MIT
 */

import type { ReportData, ReportOptions } from '../types.js';

/**
 * Generate Markdown report
 */
export function generateMarkdownReport(data: ReportData, options: ReportOptions): string {
  let md = '';

  // Header
  md += `# ${data.title}\n\n`;
  md += `> Generated by [SED](https://github.com/sgbilod/sed) - Semantic Entropy Differencing\n\n`;

  // Metadata
  md += `## Overview\n\n`;
  md += `| Property | Value |\n`;
  md += `|----------|-------|\n`;
  md += `| From | \`${data.from}\` |\n`;
  md += `| To | \`${data.to}\` |\n`;
  md += `| Generated | ${data.generatedAt.toISOString()} |\n`;
  md += `| Repository | ${data.repository.root} |\n`;
  md += `| Branch | ${data.repository.branch} |\n`;
  md += `| Commit | \`${data.repository.commit.substring(0, 8)}\` |\n`;
  md += `| Status | ${data.repository.isClean ? '✅ Clean' : '⚠️ Modified'} |\n\n`;

  // Summary Statistics
  md += `## 📊 Summary Statistics\n\n`;
  md += `| Metric | Value |\n`;
  md += `|--------|-------|\n`;
  md += `| Files Analyzed | ${data.summary.totalFiles} |\n`;
  md += `| Successful | ${data.summary.successfulAnalyses} |\n`;
  md += `| Failed | ${data.summary.failedAnalyses} |\n`;
  md += `| Lines Added | +${data.stats.additions} |\n`;
  md += `| Lines Deleted | -${data.stats.deletions} |\n`;
  md += `| Total Commits | ${data.stats.totalCommits} |\n`;
  md += `| Conventional Commits | ${data.stats.conventionalCommits} |\n`;
  md += `| Breaking Changes | ${data.stats.breakingChanges} |\n`;
  md += `| Total Entropy | ${data.summary.totalEntropy.toFixed(3)} |\n`;
  md += `| Average Entropy | ${data.summary.averageEntropy.toFixed(3)} |\n\n`;

  // Classification Distribution
  md += `## 🎯 Classification Distribution\n\n`;
  md += `| Classification | Count | Percentage |\n`;
  md += `|----------------|-------|------------|\n`;

  const total = Object.values(data.summary.classifications).reduce((a, b) => a + b, 0);
  for (const [classification, count] of Object.entries(data.summary.classifications)) {
    const percentage = total > 0 ? ((count / total) * 100).toFixed(1) : '0.0';
    const emoji = getClassificationEmoji(classification);
    md += `| ${emoji} ${classification} | ${count} | ${percentage}% |\n`;
  }
  md += '\n';

  // Visual bar (using Unicode blocks)
  if (total > 0) {
    md += '```\n';
    const barWidth = 40;
    for (const [classification, count] of Object.entries(data.summary.classifications)) {
      const filled = Math.round((count / total) * barWidth);
      const bar = '█'.repeat(filled) + '░'.repeat(barWidth - filled);
      md += `${classification.padEnd(10)} ${bar} ${count}\n`;
    }
    md += '```\n\n';
  }

  // Highest Impact Files
  md += `## ⚡ Highest Impact Files\n\n`;
  if (data.summary.highestImpact.length > 0) {
    md += `| File | Entropy | Classification |\n`;
    md += `|------|---------|----------------|\n`;
    for (const file of data.summary.highestImpact) {
      const emoji = getClassificationEmoji(file.classification);
      md += `| \`${file.file}\` | ${file.entropy.toFixed(3)} | ${emoji} ${file.classification} |\n`;
    }
  } else {
    md += `_No files analyzed_\n`;
  }
  md += '\n';

  // All Files
  md += `## 📁 All Files\n\n`;
  md += `<details>\n`;
  md += `<summary>Click to expand (${data.files.length} files)</summary>\n\n`;
  md += `| Status | File | Language | Entropy | Classification |\n`;
  md += `|--------|------|----------|---------|----------------|\n`;

  for (const file of data.files) {
    const statusEmoji = getStatusEmoji(file.status);
    const entropy = file.analysis?.metrics.totalEntropy ?? 0;
    const classification = file.analysis?.classification ?? 'unknown';
    const classEmoji = getClassificationEmoji(classification);

    if (file.error) {
      md += `| ${statusEmoji} | \`${file.file}\` | ${file.language || '-'} | ❌ Error | Failed |\n`;
    } else {
      md += `| ${statusEmoji} | \`${file.file}\` | ${file.language || '-'} | ${entropy.toFixed(3)} | ${classEmoji} ${classification} |\n`;
    }
  }

  md += `\n</details>\n\n`;

  // Commits
  if (data.commits.length > 0) {
    md += `## 📝 Commits\n\n`;
    md += `<details>\n`;
    md += `<summary>Click to expand (${data.commits.length} commits)</summary>\n\n`;

    for (const commit of data.commits.slice(0, 50)) {
      const hash = commit.hash.substring(0, 8);
      const conventional = commit.isConventional ? '✅' : '';
      md += `- \`${hash}\` ${commit.message} ${conventional}\n`;
    }

    if (data.commits.length > 50) {
      md += `\n_...and ${data.commits.length - 50} more commits_\n`;
    }

    md += `\n</details>\n\n`;
  }

  // Changelog
  if (data.changelog) {
    md += `## 📋 Changelog\n\n`;
    md += '```\n';
    md += data.changelog;
    md += '\n```\n\n';
  }

  // Footer
  md += `---\n\n`;
  md += `_Report generated by [SED](https://github.com/sgbilod/sed) v0.0.1_\n`;

  return md;
}

/**
 * Get emoji for classification
 */
function getClassificationEmoji(classification: string): string {
  const emojis: Record<string, string> = {
    trivial: '⚪',
    low: '🟢',
    medium: '🟡',
    high: '🟠',
    critical: '🔴',
  };
  return emojis[classification] || '⚫';
}

/**
 * Get emoji for status
 */
function getStatusEmoji(status: string): string {
  const emojis: Record<string, string> = {
    added: '➕',
    deleted: '➖',
    modified: '📝',
    renamed: '📋',
    copied: '📄',
  };
  return emojis[status] || '❓';
}
