/**
 * SED - Semantic Entropy Differencing
 * API Route: Export Report
 * Copyright (C) 2026 Stevo (sgbilod)
 * @license MIT
 */

import { NextRequest, NextResponse } from 'next/server';

export interface ExportRequest {
  analysisId?: string;
  format: 'json' | 'markdown' | 'html';
  includeDetails?: boolean;
}

export async function POST(request: NextRequest): Promise<NextResponse> {
  try {
    const body: ExportRequest = await request.json();
    const format = body.format || 'json';

    // Mock analysis data for export
    const analysisData = {
      from: 'HEAD~1',
      to: 'HEAD',
      timestamp: new Date().toISOString(),
      summary: {
        totalFiles: 3,
        totalEntropy: 8.5,
        averageEntropy: 2.83,
      },
      files: [
        { path: 'src/components/Button.tsx', classification: 'low', entropy: 1.2 },
        { path: 'src/utils/parser.ts', classification: 'high', entropy: 4.8 },
        { path: 'src/api/client.ts', classification: 'medium', entropy: 2.5 },
      ],
    };

    switch (format) {
      case 'markdown': {
        const markdown = generateMarkdownReport(analysisData);
        return new NextResponse(markdown, {
          headers: {
            'Content-Type': 'text/markdown',
            'Content-Disposition': 'attachment; filename="sed-report.md"',
          },
        });
      }

      case 'html': {
        const html = generateHtmlReport(analysisData);
        return new NextResponse(html, {
          headers: {
            'Content-Type': 'text/html',
            'Content-Disposition': 'attachment; filename="sed-report.html"',
          },
        });
      }

      case 'json':
      default: {
        return NextResponse.json(analysisData, {
          headers: {
            'Content-Disposition': 'attachment; filename="sed-report.json"',
          },
        });
      }
    }
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Export failed' },
      { status: 500 }
    );
  }
}

function generateMarkdownReport(data: { 
  from: string; 
  to: string; 
  timestamp: string; 
  summary: { totalFiles: number; totalEntropy: number; averageEntropy: number };
  files: Array<{ path: string; classification: string; entropy: number }>;
}): string {
  return `# SED Analysis Report

## Summary

- **From:** \`${data.from}\`
- **To:** \`${data.to}\`
- **Timestamp:** ${data.timestamp}

### Statistics

| Metric | Value |
|--------|-------|
| Total Files | ${data.summary.totalFiles} |
| Total Entropy | ${data.summary.totalEntropy.toFixed(2)} |
| Average Entropy | ${data.summary.averageEntropy.toFixed(2)} |

## Files Analyzed

${data.files.map((f) => `- **${f.path}** - ${f.classification} (${f.entropy.toFixed(2)})`).join('\n')}

---
*Generated by SED - Semantic Entropy Differencing*
`;
}

function generateHtmlReport(data: { 
  from: string; 
  to: string; 
  timestamp: string; 
  summary: { totalFiles: number; totalEntropy: number; averageEntropy: number };
  files: Array<{ path: string; classification: string; entropy: number }>;
}): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SED Analysis Report</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; }
    h1 { color: #1a1a1a; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    th, td { border: 1px solid #ddd; padding: 0.5rem; text-align: left; }
    th { background: #f5f5f5; }
    .low { color: #3b82f6; }
    .medium { color: #f59e0b; }
    .high { color: #f97316; }
    .critical { color: #ef4444; }
  </style>
</head>
<body>
  <h1>SED Analysis Report</h1>
  <p><strong>From:</strong> <code>${data.from}</code></p>
  <p><strong>To:</strong> <code>${data.to}</code></p>
  <p><strong>Timestamp:</strong> ${data.timestamp}</p>
  
  <h2>Summary</h2>
  <table>
    <tr><th>Metric</th><th>Value</th></tr>
    <tr><td>Total Files</td><td>${data.summary.totalFiles}</td></tr>
    <tr><td>Total Entropy</td><td>${data.summary.totalEntropy.toFixed(2)}</td></tr>
    <tr><td>Average Entropy</td><td>${data.summary.averageEntropy.toFixed(2)}</td></tr>
  </table>
  
  <h2>Files</h2>
  <table>
    <tr><th>Path</th><th>Classification</th><th>Entropy</th></tr>
    ${data.files.map((f) => `<tr><td>${f.path}</td><td class="${f.classification}">${f.classification}</td><td>${f.entropy.toFixed(2)}</td></tr>`).join('\n')}
  </table>
  
  <footer>
    <p><em>Generated by SED - Semantic Entropy Differencing</em></p>
  </footer>
</body>
</html>`;
}
